[package]
name = "bundlrs"
authors = ["hkau"]
license = "MIT"

version = "0.1.0"
edition = "2021"

rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-web = "4.4.1"
regex = "1.10.2"
yew = { version = "0.21.0", features = ["ssr"] }
