[package]
name = "bundlrs"
authors = ["hkau"]
license = "MIT"

version = "0.1.0"
edition = "2021"

rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-web = { version = "4.4.1" }
either = "1.9.0"
regex = "1.10.2"
sqlx = { version = "0.7.3", features = ["sqlite", "postgres", "any"]}
yew = { version = "0.21.0", features = ["ssr"] }
